name: My First Workflow

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:
    inputs:
      test:
        description: "VeryGoodDescr"
        required: true
      loglevel:
        description: "Log level"
        default: info
        type: choice
        options:
          - info
          - warning
          - debug
      testbuild:
      description:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - run: | 
          echo "This repository ${{github.repository }} contains the following files:"
          tree -a
      
